---
title: "Code to accompany RStudio 2020 lightning talk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(tidymetrics)
library(lubridate)
```

```{r import_data}
questions_raw <- read_csv("Questions.csv") %>% clean_names()
tags_raw <- read_csv("Tags.csv") %>% clean_names()

tags <- tags_raw %>% 
  filter(!is.na(tag)) %>% 
  group_by(id) %>% 
  mutate(row_number = row_number()) %>% 
  filter(row_number == 1)

questions <- questions_raw %>% 
  filter(!is.na(owner_user_id)) %>% 
  left_join(tags_raw, by = "id") %>% 
  mutate(tag = replace_na(tag, "None")) %>% 
  filter(tag %in% c("dplyr", "ggplot2", "shiny", "data.table", "regex", "python", "statistics", "package", "None")) %>% 
  mutate(date = as.Date(creation_date))
```

### cross_by_periods()

# of questions in weeks, months:
```{r}
questions %>% 
  cross_by_periods(c("week", "month")) %>% 
  summarize(nb_questions = n()) %>% 
  arrange(desc(date))
```

Rolling 28-day # of questions:
```{r}
questions %>% 
  cross_by_periods(windows = c(28)) %>% 
  summarize(nb_questions = n()) %>% 
  arrange(desc(date))
```

### cross_by_dimensions()
```{r}
questions %>% 
  cross_by_dimensions(tag) %>% 
  summarize(nb_questions = n())
```

but to really wow them, combine the two!
```{r}
questions %>% 
  cross_by_periods("week") %>% 
  cross_by_dimensions(tag) %>% 
  summarize(nb_questions = n()) %>% 
  arrange(desc(date)) %>% 
  head(20)
```

